@username = {{$dotenv USERNAME}}
@password = {{$dotenv PASSWORD}}


@clientid = {{$dotenv VITE_SPOTIFY_CLIENT_ID}}
@response_type = code
@redirect_uri = http://localhost:3000
@scope = user-read-currently-playing user-top-read
### 
#@ name authorize
GET https://accounts.spotify.com/authorize?client_id={{clientid}}&response_type={{response_type}}&redirect_uri={{redirect_uri}}&scope={{scope}}
Content-Type: application/x-www-form-urlencoded


